# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bv < Formula
  desc "butverify.dev agent CLI — publish AI-generated work for human review."
  homepage "https://butverify.dev"
  version "0.1.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/htxryan/butverify/releases/download/v0.1.3/bv_0.1.3_darwin_amd64.tar.gz"
      sha256 "a3dd7aa6661eb9c01209d8391cfe6c223c1cd3bdc15624720679c98eb1595c39"

      define_method(:install) do
        bin.install "bv"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/htxryan/butverify/releases/download/v0.1.3/bv_0.1.3_darwin_arm64.tar.gz"
      sha256 "b58301540fd6cb31b9614e9e941e7ad593374d83950879b319befda04b7992d4"

      define_method(:install) do
        bin.install "bv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/htxryan/butverify/releases/download/v0.1.3/bv_0.1.3_linux_amd64.tar.gz"
      sha256 "a9d65d5076e07808482265bda9efa7b099fbf8b37a76a2396d5af626431f0dc1"
      define_method(:install) do
        bin.install "bv"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/htxryan/butverify/releases/download/v0.1.3/bv_0.1.3_linux_arm64.tar.gz"
      sha256 "44310652a331912cc6c6d92731acc0bb4e155058c4b8dc6403bcd793250434d1"
      define_method(:install) do
        bin.install "bv"
      end
    end
  end

  test do
    system "#{bin}/bv version"
  end
end
